from collections import Counter
from copy import deepcopy

import pytest

from trading_research.v2.bindings import PINS
from trading_research.v2.gates import evaluate, eligible_for_next_stage, neighbor_rules
from trading_research.v2.ledger import Ledger, schedule, trial_identity
from trading_runtime.config import SafetyError
from .conftest import SOURCE


def passing_bundle():
    """Manually specified synthetic summary, not generated by any gate."""
    metric = {"trade_count": 500, "mean_R": .2, "profit_factor": 1.3, "max_drawdown_R": 10,
              "longest_losing_streak": 2, "indeterminate": 0, "integrity_violations": 0,
              "positive_symbol_contribution_share": .2, "positive_month_contribution_share": .1,
              "positive_trade_contribution_share": .01,
              "symbol": {f"S{i}": {"trade_count": 20} for i in range(5)},
              "year": {str(y): {"trade_count": 80, "mean_R": .2} for y in range(2016, 2027)},
              "quarter": {f"2024Q{q}": {"trade_count": 20, "mean_R": .2} for q in range(1, 5)},
              "volatility_regime": {k: {"trade_count": 50, "mean_R": .2} for k in ("LOW","NORMAL","HIGH")},
              "daily": {"SYNTHETIC_DAY": {"R": .2, "count": 1}},
              "exclude_best_trade": {"mean_R": .1}, "exclude_best_month": {"mean_R": .1},
              "exclude_best_symbol": {"mean_R": .1}}
    severe = {**metric, "mean_R": -2, "profit_factor": .2, "max_drawdown_R": 200,
              "tail_counts": {"scored_trade_count": 500, "left_tail_lt_minus_1R": 300,
                              "left_tail_lt_minus_2R": 100, "right_tail_gt_plus_1R": 10,
                              "right_tail_gt_plus_2R": 5}}
    control = {**metric, "daily": {"SYNTHETIC_DAY": {"R": .1, "count": 1}}}
    return deepcopy({"source": SOURCE, "variant": "CSLC_L30",
                     "scenarios": {"BASELINE": metric, "STRESS": metric, "SEVERE": severe},
                     "delay": metric, "controls": {c: control for c in ("BASELINE","STRESS","SEVERE")},
                     "bootstrap_lower_bound": .01,
                     "neighbors": {v: {"BASELINE": metric, "STRESS": metric, "SEVERE": severe}
                                   for v in ("CSLC_L15","CSLC_L45")},
                     "subperiods": {p: {"mean_R": .1} for p in ("2016-2017","2018-2019","2020-2021")}})


@pytest.mark.parametrize("stage", ["development","validation","internal_holdout","external_oos"])
def test_golden_all_stage_gates(spec, stage):
    result = evaluate(passing_bundle(), stage, spec)
    assert result["status"] == "PASS"
    assert result["opens_next_stage"] is False
    assert all({"reason","observed","threshold","rule"} <= r.keys() for r in result["criteria"])


@pytest.mark.parametrize("scenario", ["BASELINE","STRESS"])
@pytest.mark.parametrize("metric,value", [("mean_R",0),("profit_factor",1),("trade_count",0),
                                          ("max_drawdown_R",26),("longest_losing_streak",13),
                                          ("indeterminate",1),("integrity_violations",1)])
def test_golden_canonical_failures(spec, scenario, metric, value):
    b = passing_bundle()
    # deepcopy preserves aliasing of fixture subobjects: detach the path we mutate.
    b["scenarios"][scenario] = {**b["scenarios"][scenario], metric: value}
    r = evaluate(b, "development", spec)
    assert r["status"] == "FAIL"
    assert next(x for x in r["criteria"] if x["criterion"] == f"{scenario}.{metric}")["status"] == "FAIL"


def test_golden_c2_streak(spec):
    b = passing_bundle()
    b["scenarios"]["BASELINE"] = {**b["scenarios"]["BASELINE"], "longest_losing_streak": 12}
    b["scenarios"]["STRESS"] = {**b["scenarios"]["STRESS"], "longest_losing_streak": 13}
    assert evaluate(b, "development", spec)["status"] == "FAIL"
    b["scenarios"]["STRESS"]["longest_losing_streak"] = 12
    assert evaluate(b, "development", spec)["status"] == "PASS"


@pytest.mark.parametrize("variant", ["CSLC_L15","CSLC_L45"])
def test_golden_c2_neighbor_dd(spec, variant):
    b = passing_bundle()
    b["neighbors"][variant]["BASELINE"] = {**b["neighbors"][variant]["BASELINE"], "max_drawdown_R": 26}
    b["neighbors"][variant]["STRESS"] = {**b["neighbors"][variant]["STRESS"], "max_drawdown_R": 24}
    assert evaluate(b, "development", spec)["status"] == "FAIL"
    b["neighbors"][variant]["BASELINE"]["max_drawdown_R"] = 25
    b["neighbors"][variant]["STRESS"]["max_drawdown_R"] = 25
    assert evaluate(b, "development", spec)["status"] == "PASS"
    assert neighbor_rules(spec)[:3] == (200, 1.05, 25)


def test_golden_c4_no_tail_value_gate(spec):
    b = passing_bundle()
    assert evaluate(b, "development", spec)["status"] == "PASS"
    b["scenarios"]["SEVERE"]["tail_counts"]["left_tail_lt_minus_2R"] = 0
    assert evaluate(b, "development", spec)["status"] == "PASS"
    b["scenarios"]["SEVERE"]["tail_counts"]["left_tail_lt_minus_2R"] = 100
    assert evaluate(b, "development", spec)["status"] == "PASS"
    del b["scenarios"]["SEVERE"]["tail_counts"]
    assert evaluate(b, "development", spec)["status"] == "FAIL"  # Required reporting missing.


@pytest.mark.parametrize("key", ["positive_symbol_contribution_share","positive_month_contribution_share",
                                "positive_trade_contribution_share"])
def test_golden_concentration_gate(spec, key):
    b = passing_bundle()
    b["scenarios"]["STRESS"][key] = 1
    assert evaluate(b, "development", spec)["status"] == "FAIL"


@pytest.mark.parametrize("kind", ["symbol","month","trade"])
def test_golden_remove_best_gate(spec, kind):
    b = passing_bundle()
    b["scenarios"]["STRESS"][f"exclude_best_{kind}"]["mean_R"] = 0
    assert evaluate(b, "development", spec)["status"] == "FAIL"


@pytest.mark.parametrize("defect", ["bootstrap","delay_count","delay_mean","paired","year","subperiod","regime","symbols"])
def test_golden_additional_gates(spec, defect):
    b = passing_bundle()
    if defect == "bootstrap":
        b["bootstrap_lower_bound"] = 0
    elif defect == "delay_count":
        b["delay"] = {**b["delay"], "trade_count": 399}
    elif defect == "delay_mean":
        b["delay"] = {**b["delay"], "mean_R": 0}
    elif defect == "paired":
        b["controls"]["STRESS"]["daily"]["SYNTHETIC_DAY"]["R"] = .2
    elif defect == "year":
        b["scenarios"]["STRESS"]["year"]["2016"]["trade_count"] = 39
    elif defect == "subperiod":
        b["subperiods"]["2018-2019"]["mean_R"] = 0
    elif defect == "regime":
        b["scenarios"]["STRESS"]["volatility_regime"] = {}
    elif defect == "symbols":
        b["scenarios"]["STRESS"]["symbol"] = {}
    assert evaluate(b, "development", spec)["status"] == "FAIL"


@pytest.mark.parametrize("stage", ["validation","internal_holdout","external_oos"])
def test_golden_later_period_gate_failure(spec, stage):
    b = passing_bundle()
    s = b["scenarios"]["STRESS"]
    if stage == "internal_holdout":
        s["quarter"]["2024Q1"]["trade_count"] = 11
    else:
        s["year"]["2022" if stage == "validation" else "2025"]["mean_R"] = 0
    assert evaluate(b, stage, spec)["status"] == "FAIL"


def test_invariant_no_neighbor_promotion_or_gap(spec):
    passed = {"development": {"status": "PASS", "variant": "CSLC_L30"}}
    assert eligible_for_next_stage("CSLC_L30", passed, spec)
    assert not eligible_for_next_stage("CSLC_L15", passed, spec)
    assert not eligible_for_next_stage("CSLC_L45", passed, spec)
    assert not eligible_for_next_stage("CSLC_L30", {"validation": passed["development"]}, spec)
    passed["development"]["status"] = "FAIL"
    assert not eligible_for_next_stage("CSLC_L30", passed, spec)


def identity(spec, slot=None):
    slot = slot or schedule(spec)[0]
    result = {**PINS, **dict(zip(("stage","variant","cost_scenario","record_type","delay_minutes","subperiod"), slot)),
              "implementation_hash": "a"*64, "execution_config_hash": "b"*64,
              "dependency_fingerprint": "c"*64, "child_view_id": spec.base["bindings"]["child_view_id"],
              "parent_snapshot_id": spec.base["bindings"]["parent_snapshot_id"],
              "family": spec.base["hypotheses"][0]["id"], "purpose": "synthetic ledger conformance",
              "seed": spec.base["bootstrap"]["seed"] if slot[3] == "BOOTSTRAP" else None}
    return result


def test_golden_trial_schedule(spec):
    slots = schedule(spec)
    counts = Counter(s[3] for s in slots)
    assert len(slots) == len(set(slots)) == 53
    assert counts == {"STRATEGY":18,"DELAY_DIAGNOSTIC":4,"TIME_MATCHED_SPY":12,
                      "NO_TRADE":4,"BOOTSTRAP":6,"SUBPERIOD":9}
    assert all(s[1] == "CSLC_L30" for s in slots if s[0] != "development")


def test_invariant_trial_resume_and_changed_code(spec, tmp_path):
    value = identity(spec)
    original = trial_identity(value, spec)[0]
    ledger = Ledger(tmp_path, spec)
    a = ledger.begin(value, source=SOURCE)
    b = ledger.begin(value, source=SOURCE)
    assert a["trial_id"] == b["trial_id"] == original
    assert (a["attempt"], b["attempt"]) == (1,2)
    ledger.finish(original, 2, status="PASS", outcome_hash="d"*64)
    assert len(ledger.read()) == 3
    changed = {**value, "implementation_hash": "e"*64}
    assert trial_identity(changed, spec)[0] != original
    with pytest.raises(SafetyError, match="SLOT_ALREADY"):
        ledger.begin(changed, source=SOURCE)
    with pytest.raises(SafetyError, match="ATTEMPT"):
        ledger.finish(original, 2, status="PASS", outcome_hash="f"*64)


def test_invariant_budget_overflow(spec, tmp_path):
    ledger = Ledger(tmp_path, spec)
    for slot in schedule(spec):
        ledger.begin(identity(spec, slot), source=SOURCE)
    with pytest.raises(SafetyError, match="BUDGET_OVERFLOW"):
        ledger.begin({**identity(spec), "execution_config_hash": "f"*64}, source=SOURCE)
    assert len(ledger.read()) == 53


def test_invariant_ledger_tamper_and_partial(spec, tmp_path):
    ledger = Ledger(tmp_path, spec)
    ledger.begin(identity(spec), source=SOURCE)
    (tmp_path/".partial-incomplete").write_bytes(b'{"incomplete"')
    assert len(ledger.read()) == 1
    p = tmp_path/"event-00000000.json"
    p.write_bytes(p.read_bytes().replace(b"ATTEMPT_STARTED", b"FAIL"))
    with pytest.raises(SafetyError, match="CORRUPT"):
        ledger.read()


def test_invariant_ledger_writer_lock(spec, tmp_path):
    ledger = Ledger(tmp_path, spec)
    (tmp_path/".writer.lock").touch()
    with pytest.raises(SafetyError, match="WRITER_ACTIVE"):
        ledger.begin(identity(spec), source=SOURCE)


@pytest.mark.parametrize("key", [*PINS, "child_view_id","parent_snapshot_id"])
def test_invariant_trial_binding_mismatch(spec, key):
    value = identity(spec)
    value[key] = "0"*64
    with pytest.raises(SafetyError):
        trial_identity(value, spec)


def test_invariant_unregistered_trial_and_real_ledger(spec, tmp_path):
    with pytest.raises(SafetyError):
        trial_identity({**identity(spec), "variant": "CSLC_L60"}, spec)
    with pytest.raises(SafetyError, match="REAL_DATA"):
        Ledger(tmp_path, spec).begin(identity(spec), source="ALPACA")
